FROM nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04

RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list


RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    wget    \
    ninja-build \
    git

RUN mkdir -p /code/gtrace
ADD ./ /code/gtrace
WORKDIR /code/gtrace


RUN wget https://cmake.org/files/v3.27/cmake-3.27.7-linux-x86_64.tar.gz \
    && tar -zxvf cmake-3.27.7-linux-x86_64.tar.gz \
    && mv cmake-3.27.7-linux-x86_64 cmake-3.27.7 \
    && ln -sf /cmake-3.27.7/bin/* /usr/bin

ENV PATH="/code/gtrace/cmake-3.27.7/bin:${PATH}"

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    && pip install torch==1.12.0 torchaudio==0.12.0 torchvision==0.13.0 --index-url https://download.pytorch.org/whl/cu116

# RUN pip install torch==1.12.0 torchaudio==0.12.0 torchvision==0.13.0 --index-url https://download.pytorch.org/whl/cu116

RUN pip install -r requirements.txt

RUN pip install  dgl -f https://data.dgl.ai/wheels/cu116/repo.html \
    && pip install  dglgo -f https://data.dgl.ai/wheels-test/repo.html

# RUN pip install -r requirements.txt
